### ISSUE TITLE
Compatibility with Better NPC Sheet 5E

### ISSUE THREAD

**Issue by Norc** [Stryxin/dnd5edark-foundryvtt#2]
When only Better NPC Sheet 5E 0.7.6 and DND5E Dark Mode 2.0.2 are installed (Foundry 0.5.7), Dark Mode is not applied to NPC character sheets:

![image](https://user-images.githubusercontent.com/64667579/82134161-b5564180-97c2-11ea-8d32-63a48bbf7f45.png)

**Comment by Stryxin** [comment]
That's sort of intentional, if someone wants to use full Dark Mode I don't see why would you want specific sheet to stay light, so use "Dark" version of the sheet instead (go to sheet settings and there BetterNPCActor5eSheetDark" version:
![image](https://user-images.githubusercontent.com/60761741/82209272-49ccbb00-990d-11ea-9553-5fca67d9714c.png)

 I would have to copy a lot of lines of code that would just bloat the file for no real benefit.

**Comment by Norc** [comment]
Right, I saw that myself later after logging the issue and it's working great, thanks!
