### ISSUE TITLE
Dark Letters in Base Character Sheet

### ISSUE THREAD

**Issue by MrVauxs** [Stryxin/dnd5edark-foundryvtt#6]
![image](https://user-images.githubusercontent.com/32039708/85336897-bffda800-b4df-11ea-844b-e75d60c516a7.png)
As seen and showcased in the image, the text is nearly unreadable due to that style change, and probably should be white instead of black like in Hit Dice and Initiative. Version 2.0.5. No errors or relevant to dnd5edark warnings in console.

**Comment by Stryxin** [comment]
Tidy5e Sheet issue not darkmode issue, activate darkmod in Tidy5e settings or disable it 
 
Peter "Stryxin" Peko,
Artist / Content Creator,
Forgotten Adventures <https://www.patreon.com/forgottenadventures>
 
______________________________________________________________
> Od: "MrVauxs" <notifications@github.com>
> Komu: "Stryxin/dnd5edark-foundryvtt" <dnd5edark-foundryvtt@noreply.github.com>
> Datum: 22.06.2020 23:28
> Předmět: [Stryxin/dnd5edark-foundryvtt] Dark Letters in Base Character Sheet (#6)
>
 
 <https://user-images.githubusercontent.com/32039708/85336897-bffda800-b4df-11ea-844b-e75d60c516a7.png>
 As seen and showcased in the image, the text is nearly unreadable due to that style change, and probably should be white instead of black like in Hit Dice and Initiative. Version 2.0.5. No errors or relevant to dnd5edark warnings in console.
